FILES=cadena1.dat cadena2.dat cadena3.dat cadena4.dat cadena5.dat cadena6.dat cadena7.dat cadena8.dat

PLOTS:{FILES}
	python3 archivo lectura
	
{FILES}: punto1.c
	gcc punt1.c -fopenmp -lm -o punto1
	./punto1
